language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    global:
        - TEST_COMMAND="composer test"

matrix:
    fast_finish: true
    include:
        - php: 5.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - $TEST_COMMAND
